### ISSUE TITLE
Planned Payment 

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#716] opened 2022-04-13 03:24 UTC
Planned Account Transfer from one account to another.

**Comment by b4allb4u** [comment] 2022-04-21 12:34
@ivywallet, Hi Team, 
If possible, Pls show the total amount of Planned Payments also.

**Comment by StarHamster** [comment] 2022-04-23 11:56
Duplicate of #173

**Closed by StarHamster** 2022-04-23 11:56 UTC
Labels: duplicate
