### ISSUE TITLE
[feature] Joint accounting

### ISSUE THREAD

**Issue by silentiumNoxe** [ILIYANGERMANOV/ivy-wallet#803] opened 2022-04-28 11:51 UTC
**What do you want to be added or improved?**
As a user, I want to suggest a feature - joint accounting. I've living with my wife and want to manage a budget with her.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- Improving management

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- You already registered users with Google account. Let's share some money accounts with another user.

**Comment by StarHamster** [comment] 2022-04-28 14:44
Duplicate of #74

**Closed by StarHamster** 2022-04-28 14:44 UTC
Labels: duplicate
