### ISSUE TITLE
Language Choices 

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#419] opened 2022-01-09 18:11 UTC
It would be a great ideea if the app i've just purchased, would have the setting of changing the language in my language. 

For me it would be great a Romanian translation, but that would be awesome for other users to have more options. 

Hope to see some improvements in the future! 
Thank you in advance! 

With love, C.T. Solomon!

**Comment by StarHamster** [comment] 2022-04-18 19:18
Duplicate of #342

**Closed** 2022-04-18 19:19 UTC
