### ISSUE TITLE
Auto Sync For Different Devices

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#753] opened 2022-04-20 01:31 UTC
I use this app on my phone and had just bought a tablet. I find it easier to use the app on the tablet since it has a bigger screen. I just noticed that the edits i make here doesn't automatically reflect in the tablet with the same account.

**Comment by StarHamster** [comment] 2022-04-20 15:01
Duplicate of #286

**Closed** 2022-04-20 15:06 UTC
