### ISSUE TITLE
Custom account categorizations

### ISSUE THREAD

**Issue by nurhusni** [ILIYANGERMANOV/ivy-wallet#526] opened 2022-02-14 08:33 UTC
**What do you want to be added or improved?**
As a user I want to have an account categorization where I can categorize multiple accounts. For example, I have 3 bank saving accounts, I would like to categorize them into "Bank" category where I can also see the total balance, income, and expense in that category. By default, it'd be nice if I can set a same icon for all accounts in that category.

As of now, I have 12 accounts (including Cash). It looks convoluted and is quite tiring for me to scroll all the way down to find an account. Those 12 accounts can actually be categorized into 3 categorizations.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- Easier to access an account, so I don't need scroll all the way down to find a specific account
- Easier to manage your accounts and see the total breakdown of your accounts

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- User would go to "accounts" tab where they would find the list of account categories. By clicking one of the category, users would find the list of accounts within that category.
- User can also decide if they would see the list of the all of the accounts on the "account" tab directly without having to go to each category.

**Comment by ILIYANGERMANOV** [comment] 2022-02-14 08:37
Hi, that's great idea! Check #177 it's similar. We'll implement it for sure it just takes time as I'm the only developer on the project + the great Ivy Wallet open-source community. 

If we expand our dev community we can really build great things!

**Comment by StarHamster** [comment] 2022-04-23 09:51
Duplicate of #177

**Closed by StarHamster** 2022-04-23 09:51 UTC
Labels: duplicate, user request
