### ISSUE TITLE
Reminders For Upcoming Payments

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#567] opened 2022-03-03 18:38 UTC
A reminders functionality for upcoming planned payments so I'm notified about them in advance. Thanks 🙏

**Comment by edsnchz** [comment] 2022-03-06 08:48
+1

**Comment by StarHamster** [comment] 2022-04-23 09:25
Duplicate of #232

**Closed by StarHamster** 2022-04-23 09:25 UTC
Labels: duplicate
