### ISSUE TITLE
Credit Card option .

### ISSUE THREAD

**Issue by johnmelodyme** [ILIYANGERMANOV/ivy-wallet#884] opened 2022-05-10 03:48 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to request a credit card feature where we can insert c how much we spend , how much of the balance left and able to record if I pay the card with a bank account (transfer)

### Why do you need it?

- easy to calculate the credit card expenses.
- a better data collection yet to be export to csv.

### How do you imagine it?

credit card feature same as the loan feature.

**Comment by StarHamster** [comment] 2022-05-10 05:53
Duplicate of #11

**Closed by StarHamster** 2022-05-10 05:53 UTC
Labels: duplicate
