### ISSUE TITLE
Please Add Message Sync Functionality: Optional

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#379] opened 2022-01-03 12:29 UTC
It would be helpful if, after scanning the messages, it automatically adds it as an expense or income. Or atleast show user an option to choose from the notification panel.

It will definitely minimise the tedious way of entering the data, manually.

**Comment by StarHamster** [comment] 2022-04-23 10:54
Duplicate of #351

**Closed by StarHamster** 2022-04-23 10:54 UTC
Labels: duplicate
