### ISSUE TITLE
An Option To Choose Whether A Category Is Expense Or Income

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#866] opened 2022-05-08 09:32 UTC
When you create a new category, it would be helpful to have an option of it being an expense or income, as I find the default being both a waste of space and visually confusing. The option could go where you choose the name and colour of a category when setting it up.

**Comment by StarHamster** [comment] 2022-05-08 10:27
Duplicate of #199

**Closed by StarHamster** 2022-05-08 10:27 UTC
Labels: duplicate
