### ISSUE TITLE
Hi ..I Love This App It's Really Amazing I'd Recommend It To Everyone I Know If Only It Support Arabic Language ..So Please Support Arabic As Soon As possible.. Thank You ❤️

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#618] opened 2022-03-19 02:38 UTC

**Comment by StarHamster** [comment] 2022-04-18 19:01
Duplicate of #447

**Closed** 2022-04-18 19:21 UTC
