### ISSUE TITLE
Helping App Translation

### ISSUE THREAD

**Issue by stepersano** [ILIYANGERMANOV/ivy-wallet#492] opened 2022-02-01 13:27 UTC
Hi, I am an Italian user that find your app really good... I wanted to contribute to the translation of the app in Italian. How can I do it? 
Thank you! Have a good day.
Greate App!! Bravo!

**Comment by ILIYANGERMANOV** [comment] 2022-02-03 08:30
Thank you @stepersano! We'll start work on translations after the Graphs & Charts feature. I'll ping you when our localization code is ready so you can help us with Italian. Your help is much appreciated  :)

**Comment by ayesse** [comment] 2022-03-07 20:47
I'd like to contribute with italian translation as well, if needed :)

**Comment by ILIYANGERMANOV** [comment] 2022-03-07 20:52
You guys and girls are awesome! I'll do my best to setup community Telegram group and organization so you can collaborate and make a great open-source and free product!

Yes, we'll make the app free and setup donations to a development fund :)

**Comment by StarHamster** [comment] 2022-04-18 19:07
Duplicate of #342

@stepersano and @ayesse, here is [a link to the mentioned Telegram Community](https://t.me/+ETavgioAvWg4NThk). Maybe one day there will be news about the possibility of translation

**Closed** 2022-04-18 19:19 UTC
Labels: dev
