### ISSUE TITLE
[FEATURES] Translate into spanish

### ISSUE THREAD

**Issue by jevo160296** [ILIYANGERMANOV/ivy-wallet#859] opened 2022-05-06 17:09 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want the app in spanish

### Why do you need it?

- It will be easier to understand the app

### How do you imagine it?

App in spanish

**Comment by jevo160296** [comment] 2022-05-06 17:09
I'm working on it

**Comment by StarHamster** [comment] 2022-05-07 11:10
Duplicate of #179

**Closed by StarHamster** 2022-05-07 11:10 UTC
Labels: duplicate

**Comment by StarHamster** [comment] 2022-05-07 11:12
@jevo160296, hello! As far as I know @Pkcarreno has already working on it too

**Comment by jevo160296** [comment] 2022-05-07 11:34
Ok thanks!, I'll contact him maybe we can finish it faster together.
