### ISSUE TITLE
[BUG] Jetpack Compose doesn't show "Cursor handle" when inputting text

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#160] opened 2021-11-19 21:04 UTC

**Comment by ILIYANGERMANOV** [comment] 2021-11-19 21:22
Jetpack Compose Input field doesn't support Cursor handler, yet :/ If someone knows how to fix/workaround that I'd be extremely grateful!

**Comment by MohitMandalia** [comment] 2022-03-28 18:57
I would like to check on it if i can find some workaround so basically when we enter amount there is no cursor is that the issue here?

**Comment by ILIYANGERMANOV** [comment] 2022-03-28 19:00
Hi @MohitMandalia the issue is that the Title & Description input fields doesn't have a cursor handle because the new jetpack compose input fields doesn't support it.
 
What I did as workaround is to use ported EditText but that has different issues. Feel free to try finding a workaround on this :) It'll be major improvement!

**Comment by MohitMandalia** [comment] 2022-03-28 19:03
sure will try to come up with some workaround if I can.
Thanks for the explanation.

**Comment by MohitMandalia** [comment] 2022-03-28 20:48
Can I get a context on where exactly this issue exist I am new to compose and tried to use BasicTextField in other project  and has a blinking cursor handle could you please guide me with the problem so I can look for some alternative.

**Comment by ILIYANGERMANOV** [comment] 2022-03-28 20:49
Great question! I just checked it out and it was fixed by the latest Jetpack Compose update!! Amazing 🚀

**Comment by MohitMandalia** [comment] 2022-03-28 20:50
okk cool.

No worries.

**Closed by ILIYANGERMANOV** 2022-03-28 20:49 UTC
Labels: bug, improvement, user request, ux, good first issue, help wanted
