### ISSUE TITLE
Planned Transfer

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#272] opened 2021-12-21 03:58 UTC

**Comment by Bilal2423** [comment] 2021-12-21 03:59
Like planes expense and income , planned transfer are for my SIPs , every month on 10 for Investment and Sometimes I move to another wallet for Saving Purpose

**Comment by StarHamster** [comment] 2022-04-23 11:54
Duplicate of #173

**Closed by StarHamster** 2022-04-23 11:54 UTC
Labels: duplicate
