### ISSUE TITLE
Can add Import From MoneyWallet, Here Is The Link https://play.google.com/store/apps/details?id=com.oriondev.moneywallet

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#443] opened 2022-01-20 04:12 UTC

**Comment by azazelazay** [comment] 2022-01-20 11:28
Issue is already listed @ #395

I also tried filling the ivy exported csv with moneywallet's data, but sadly import fails.

**Comment by StarHamster** [comment] 2022-04-23 10:38
Duplicate of #395

**Closed by StarHamster** 2022-04-23 10:38 UTC
Labels: duplicate
