### ISSUE TITLE
Feature to set Planned Account Transfers.

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#829] opened 2022-05-02 06:22 UTC

**Comment by shahiljain** [comment] 2022-05-02 06:51
I was just going to make a request for this ... Thanks!

**Comment by Jai-mTm** [comment] 2022-05-03 17:04
+1

**Comment by husseinaltaaf** [comment] 2022-05-04 09:43
+1

**Comment by husseinaltaaf** [comment] 2022-05-04 09:44
This feature has been requested by many of us, users... since very long time ago. I don't know why the developers isn't considering this feature as urgent or something like that!

**Comment by Sumat2222** [comment] 2022-05-07 09:39
+1 please

**Comment by StarHamster** [comment] 2022-05-07 20:03
Duplicate of #173

**Closed by StarHamster** 2022-05-07 20:03 UTC
Labels: duplicate
