### ISSUE TITLE
Option for save multiple filters for next time [FEATURES] ...

### ISSUE THREAD

**Issue by jdwarraich** [ILIYANGERMANOV/ivy-wallet#891] opened 2022-05-12 09:50 UTC
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have presets filter that i can edit or add a new one

### Why do you need it?

-  Every time i go to see reports ,i have to selects all filters/option again and again

**Comment by StarHamster** [comment] 2022-05-13 10:03
Duplicate of #891

**Comment by StarHamster** [comment] 2022-05-13 10:04
Duplicate of #500

**Closed by StarHamster** 2022-05-13 10:03 UTC
Labels: duplicate
