### ISSUE TITLE
How to access the pre-made categories list again?

### ISSUE THREAD

**Issue by MicaelJarniac** [ILIYANGERMANOV/ivy-wallet#677] opened 2022-04-05 04:21 UTC
During first time setup, there was a nice list of pre-made categories for me to choose from. I chose just a few.

Shortly after finishing first time setup, I realized I wanted some other categories from that list.

How can I bring that list back, to pick more categories from it?

When I try to add a new category, it seems to bring up a completely empty one for me to manually fill all the details.

**Comment by StarHamster** [comment] 2022-04-21 10:59
Duplicate of #279

**Closed by StarHamster** 2022-04-21 10:59 UTC
Labels: duplicate
